Arrays
OreyM/phplab-tasks-2022 pull request #6
Opened 2022-08-11 13:03 UTC by OreyM

Arrays task has resolved

2022-08-15 22:20 UTC, Kloud333 requested changes
Загалом не погано. 👍 Два маленьких виправленняю

2022-08-15 22:20 UTC, Kloud333 commented on src/arrays/Arrays.php
> +        foreach ($input as $el) {
Краще не називати змінну $el.

2022-08-15 22:20 UTC, Kloud333 commented on src/arrays/Arrays.php
> +}
Додай пустий рядок у кінці. Навіть github підказує.

2022-08-16 09:23 UTC, OreyM commented on src/arrays/Arrays.php
> +        foreach ($input as $el) {
виправлено

2022-08-16 09:23 UTC, OreyM commented on src/arrays/Arrays.php
> +}
виправлено

2022-08-19 21:16 UTC, Kloud333 requested changes

2022-08-19 21:16 UTC, Kloud333 commented on src/arrays/Arrays.php
> +    public function groupByTag(array $input): array
Доволі скоадний алгоритм.
Спробуй зробити наступним шляхом:

Створи нову змінну
Відсортуй масив
Зроби перебір по айтемам -> і у середині зроби перебір по тегам айтема і запиши айтем нейм у створи нову змінну вище - $tags[$tag][] = $item['name']; - приблизно
Відсортуй новий масив і поверний його.

2022-08-20 09:47 UTC, OreyM commented on src/arrays/Arrays.php
> +    public function groupByTag(array $input): array
Згоден. Щось я заморочився і наробив купу зайвих рухів. А все набагато простіше. Заодно підправив типізації та іменування змінних у двох попередніх методах.

2022-08-27 23:09 UTC, Kloud333 commented on src/arrays/Arrays.php
> +    public function groupByTag(array $input): array
Супер! 👍 Молодець.

2022-08-27 23:09 UTC, Kloud333 approved these changes

2022-08-28 10:24 UTC, merged