Functions
OreyM/phplab-tasks-2022 pull request #8
Opened 2022-08-12 13:15 UTC by OreyM

Functions task has resolved

2022-08-15 22:50 UTC, Kloud333 requested changes

2022-08-15 22:50 UTC, Kloud333 commented on composer.json
> +        "fzaninotto/faker": "^1.5"
Чомусь не памятаю, щоб у завданні було вказано використовувати якісь бібліотеки. . .

2022-08-15 22:50 UTC, Kloud333 commented on src/functions/Functions.php
> +        if (is_scalar($arg)) return $this->sayHelloArgument($arg);
Поганий запис. if повинен бути завжди з розділлючими дужками.  
Також не памятаю, щоб цей рядок - **return $this->sayHelloArgument($arg);** треба було міняти. 
Він мав залишитись таким як і був.

2022-08-15 22:50 UTC, Kloud333 commented on src/functions/Functions.php
> +            if (is_string($arg)) return $arg;
Також тут - поганий варіант запису. Розділяй if та return. Дуже погано читається.

2022-08-15 22:50 UTC, Kloud333 commented on src/functions/Functions.php
>  }
Додай постий рядок у кінці.

2022-08-15 22:50 UTC, Kloud333 commented on tests/CountArgumentsTest.php
> +class CountArgumentsTest extends TestCase
Цей тест не проходить. Зроби будь-ласка так, щоб проходив.

2022-08-15 22:50 UTC, Kloud333 commented on tests/SayHelloArgumentWrapperTest.php
> +        $this->expectExceptionMessage(
Не обовязково писати окремий тест, щоб зробити перевірку на меседж. Краще цю ж перевірку додай у минулий тест рід перевіркою на Ексепшн. + сам меседж краще винести у змінну. Так буде потім легше редагувати тест у майбутньому і код буде виглядати лаконічніше.

2022-08-15 22:50 UTC, Kloud333 commented on tests/SayHelloArgumentWrapperTest.php
> +}
Пустий рядок.

2022-08-16 11:35 UTC, OreyM commented on composer.json
> +        "fzaninotto/faker": "^1.5"
Виправив. Згоден, погана ініціатива. Ще й тести поломало...

2022-08-16 11:35 UTC, OreyM commented on src/functions/Functions.php
> +        if (is_scalar($arg)) return $this->sayHelloArgument($arg);
виправлено

2022-08-16 11:35 UTC, OreyM commented on src/functions/Functions.php
> +            if (is_string($arg)) return $arg;
Виправлено

2022-08-16 11:36 UTC, OreyM commented on src/functions/Functions.php
>  }
Виправлено

2022-08-16 11:36 UTC, OreyM commented on tests/CountArgumentsTest.php
> +class CountArgumentsTest extends TestCase
Виправлено. Зробив звичайні масиви

2022-08-16 12:01 UTC, OreyM commented on tests/SayHelloArgumentWrapperTest.php
> +        $this->expectExceptionMessage(
зроблено

2022-08-16 12:01 UTC, OreyM commented on tests/SayHelloArgumentWrapperTest.php
> +}
додано

2022-08-19 21:29 UTC, Kloud333 requested changes
Загалом тести гаразд. Додав декілька маленьких коментарів.

2022-08-19 21:29 UTC, Kloud333 commented on src/functions/Functions.php
> +            return $arg;
Завжди перед return роби пропуск. Цікавий алгоритм. Але я б тут не використав оператор "..." а у тесті. 🤔

2022-08-19 21:29 UTC, Kloud333 commented on tests/CountArgumentsTest.php
> +
Зайвий пустий рядок.

2022-08-19 21:29 UTC, Kloud333 commented on tests/CountArgumentsWrapperTest.php
> +
Зайвий пустий рядок.

2022-08-19 21:29 UTC, Kloud333 commented on tests/SayHelloArgumentTest.php
> +
Зайвий пустий рядок.

2022-08-19 21:29 UTC, Kloud333 commented on tests/SayHelloArgumentWrapperTest.php
> +
Зайвий пустий рядок.

2022-08-19 21:29 UTC, Kloud333 commented on tests/SayHelloArgumentWrapperTest.php
> +
Зайвий пустий рядок.

2022-08-19 21:29 UTC, Kloud333 commented on tests/SayHelloArgumentWrapperTest.php
> +        $this->functions->sayHelloArgumentWrapper($input);
Тут я б використав оператор "...".

2022-08-27 23:12 UTC, Kloud333 approved these changes

2022-08-28 10:23 UTC, merged